'use client';
import { Inter } from "next/font/google";
import "./globals.css";
import SocketProvider from "@/context/SocketContext";
import { Toaster } from "react-hot-toast";
import { useEffect } from 'react';
import AOS from 'aos';
import 'aos/dist/aos.css';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init({
      duration: 1000, // Animation duration
      once: true, // Whether animation should happen only once
      mirror: false, // Whether elements should animate out while scrolling past them
    });
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SocketProvider>
          <Toaster />
          {children}
        </SocketProvider>
      </body>
    </html>
  );
}
